ログイン・ログアウト機能実装
shinonome-inc/backend-final-assignment-Koshi pull request #2
Opened 2023-08-19 09:35 UTC by Yoshida-koshi

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-08-19 12:51 UTC, i-mak33-124 commented
とてもよく書けていると思います。細かい点ですがコメントを一件行ったので確認・修正をお願いします。

2023-08-19 18:45 UTC, i-mak33-124 commented on accounts/tests.py
> +        User.objects.create_user(username="testuser", password="testpassword")
self.user = User.objects.create_user(username="testuser", password="testpassword")
はsetUpに書いた方がコードの重複がなくなるので良いと思います。

2023-08-20 01:41 UTC, IzmYuta requested changes
非常によく書けています！
ただ数点直してほしい部分があるのでそこだけ修正お願いします！🙏

2023-08-20 01:41 UTC, IzmYuta commented on accounts/tests.py
> +from mysite import settings
settingsモジュールはdjango.confからインポートするようにしましょう。
理由は単純でmysiteにsettingsファイルが置いてあるとは限らないからです。
```suggestion
from django.conf import settings
```

2023-08-20 01:41 UTC, IzmYuta commented on accounts/views.py
> +from mysite import settings
同様

2023-08-20 01:41 UTC, IzmYuta commented on templates/base.html
> +      <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
ログイン状況に応じて、Loginだけ・Logoutだけ表示させると親切かもしれません。

2023-08-20 01:50 UTC, IzmYuta commented
Webブラウザ上でProfileにアクセスする方法が現状URL直打ちしかないのが気になりました。Home画面のテンプレートにProfileへのリンクを置いておくと親切かもしれません。
次の課題でもProfileの実装はするので、面倒なら飛ばしてOKです。

2023-08-20 03:13 UTC, Yoshida-koshi commented on accounts/tests.py
> +        User.objects.create_user(username="testuser", password="testpassword")
self.userをsetUpにおいてコードをまとめました！[2f6e1ca](https://github.com/shinonome-inc/backend-final-assignment-Koshi/pull/2/commits/2f6e1caf36d21e9bf3d930dee76e091af3d7e8d2)

2023-08-20 03:13 UTC, Yoshida-koshi commented on accounts/tests.py
> +from mysite import settings
mysiteからdjango.confに変更しました！[5db26b5](https://github.com/shinonome-inc/backend-final-assignment-Koshi/pull/2/commits/5db26b596c8a48f4bf5bd86b686ee23d0c57a1f3)

2023-08-20 03:14 UTC, Yoshida-koshi commented on accounts/views.py
> +from mysite import settings
こちらも同様に変更しました！[5db26b5](https://github.com/shinonome-inc/backend-final-assignment-Koshi/pull/2/commits/5db26b596c8a48f4bf5bd86b686ee23d0c57a1f3)

2023-08-20 03:19 UTC, Yoshida-koshi commented on templates/base.html
> +      <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
ログイン状況に応じてLoginだけ・Logoutだけを表示させました！[e282086](https://github.com/shinonome-inc/backend-final-assignment-Koshi/pull/2/commits/e282086a105d349059429aeddef032a483741493)

| ログイン時 | 未ログイン時 |
| ---------- | ---------- |
| <img src="https://github.com/shinonome-inc/backend-final-assignment-Koshi/assets/85224998/03c8f1e9-e837-48a6-a3fc-e48070a95d84" width="300"> | <img src="https://github.com/shinonome-inc/backend-final-assignment-Koshi/assets/85224998/8be2366b-4edb-450b-bfc4-340e971608ab" width="300"> |

2023-08-20 03:22 UTC, Yoshida-koshi commented
ログイン時の時のみHome画面からProfile画面に飛べるようにHome画面にリンクを貼りました！[328a6c0](https://github.com/shinonome-inc/backend-final-assignment-Koshi/pull/2/commits/328a6c0fd628098369f81aee54d5a1e56a2cd887)

| ログイン時 | 未ログイン時 |
| ---------- | ---------- | 
| <img src="https://github.com/shinonome-inc/backend-final-assignment-Koshi/assets/85224998/9a9f794a-8cae-4ce6-be06-d942ed41e9ef" width="300"> | <img src="https://github.com/shinonome-inc/backend-final-assignment-Koshi/assets/85224998/c241af3a-ba46-4572-bb70-91eaaf976af3" width="300"> |

2023-08-20 05:03 UTC, IzmYuta approved these changes

2023-08-20 05:04 UTC, merged